<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;
use App\Models\User;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener el primer admin para asignar como creador
        $admin = User::whereHas('roles', function ($query) {
            $query->where('name', 'admin');
        })->first();

        $customers = [
            // Clientes individuales
            [
                'customer_code' => 'CLI-2025-0001',
                'customer_type' => 'individual',
                'first_name' => 'Juan',
                'last_name' => 'Pérez Rodríguez',
                'tax_id' => '001-0012345-6',
                'email' => 'juan.perez@email.com',
                'phone' => '809-555-1234',
                'mobile' => '829-555-1234',
                'address' => 'Calle Principal #123, Los Jardines',
                'city' => 'Santo Domingo',
                'state' => 'Distrito Nacional',
                'postal_code' => '10101',
                'notes' => 'Cliente frecuente, prefiere reparaciones rápidas',
                'status' => true,
                'payment_terms' => 0,
                'credit_limit' => 0,
                'created_by' => $admin?->id,
            ],
            [
                'customer_code' => 'CLI-2025-0002',
                'customer_type' => 'individual',
                'first_name' => 'María',
                'last_name' => 'González',
                'tax_id' => '001-0023456-7',
                'email' => 'maria.gonzalez@email.com',
                'phone' => '809-555-2345',
                'mobile' => '829-555-2345',
                'address' => 'Av. Churchill #456',
                'city' => 'Santo Domingo',
                'state' => 'Distrito Nacional',
                'postal_code' => '10102',
                'notes' => 'Siempre solicita garantía extendida',
                'status' => true,
                'payment_terms' => 0,
                'credit_limit' => 0,
                'created_by' => $admin?->id,
            ],
            [
                'customer_code' => 'CLI-2025-0003',
                'customer_type' => 'individual',
                'first_name' => 'Carlos',
                'last_name' => 'Martínez Santos',
                'tax_id' => '001-0034567-8',
                'email' => 'carlos.martinez@email.com',
                'phone' => '809-555-3456',
                'mobile' => '829-555-3456',
                'address' => 'Calle El Conde #789',
                'city' => 'Santo Domingo',
                'state' => 'Distrito Nacional',
                'postal_code' => '10103',
                'notes' => 'Cliente corporativo independiente',
                'status' => true,
                'payment_terms' => 15,
                'credit_limit' => 50000,
                'created_by' => $admin?->id,
            ],

            // Clientes empresariales
            [
                'customer_code' => 'CLI-2025-0004',
                'customer_type' => 'company',
                'company_name' => 'Tecnología Avanzada SRL',
                'first_name' => 'Roberto',
                'last_name' => 'Fernández',
                'tax_id' => '130-12345-6',
                'email' => 'contacto@tecavanzada.com',
                'phone' => '809-555-4567',
                'mobile' => '829-555-4567',
                'address' => 'Av. Winston Churchill #1000, Torre Empresarial, Piso 5',
                'city' => 'Santo Domingo',
                'state' => 'Distrito Nacional',
                'postal_code' => '10104',
                'website' => 'https://www.tecavanzada.com',
                'notes' => 'Contrato de mantenimiento anual',
                'status' => true,
                'payment_terms' => 30,
                'credit_limit' => 150000,
                'created_by' => $admin?->id,
            ],
            [
                'customer_code' => 'CLI-2025-0005',
                'customer_type' => 'company',
                'company_name' => 'Consultores Informáticos CA',
                'first_name' => 'Ana',
                'last_name' => 'Jiménez',
                'tax_id' => '130-23456-7',
                'email' => 'admin@consultoresti.com',
                'phone' => '809-555-5678',
                'mobile' => '829-555-5678',
                'address' => 'Calle Gustavo Mejía Ricart #234',
                'city' => 'Santo Domingo',
                'state' => 'Distrito Nacional',
                'postal_code' => '10105',
                'website' => 'https://www.consultoresti.com',
                'notes' => 'Cliente VIP - prioridad alta',
                'status' => true,
                'payment_terms' => 45,
                'credit_limit' => 250000,
                'created_by' => $admin?->id,
            ],
            [
                'customer_code' => 'CLI-2025-0006',
                'customer_type' => 'company',
                'company_name' => 'Soluciones Digitales EIRL',
                'first_name' => 'Pedro',
                'last_name' => 'Ramírez',
                'tax_id' => '130-34567-8',
                'email' => 'info@solucionesdigitales.do',
                'phone' => '809-555-6789',
                'mobile' => '829-555-6789',
                'address' => 'Av. 27 de Febrero #567',
                'city' => 'Santo Domingo',
                'state' => 'Distrito Nacional',
                'postal_code' => '10106',
                'website' => 'https://www.solucionesdigitales.do',
                'notes' => 'Requiere facturación con NCF',
                'status' => true,
                'payment_terms' => 30,
                'credit_limit' => 100000,
                'created_by' => $admin?->id,
            ],
            [
                'customer_code' => 'CLI-2025-0007',
                'customer_type' => 'company',
                'company_name' => 'Grupo Empresarial TechPro',
                'first_name' => 'Luis',
                'last_name' => 'Morales',
                'tax_id' => '130-45678-9',
                'email' => 'ventas@techpro.com.do',
                'phone' => '809-555-7890',
                'mobile' => '829-555-7890',
                'address' => 'Calle John F. Kennedy #890',
                'city' => 'Santo Domingo',
                'state' => 'Distrito Nacional',
                'postal_code' => '10107',
                'website' => 'https://www.techpro.com.do',
                'notes' => 'Múltiples sucursales',
                'status' => true,
                'payment_terms' => 60,
                'credit_limit' => 300000,
                'created_by' => $admin?->id,
            ],
            [
                'customer_code' => 'CLI-2025-0008',
                'customer_type' => 'individual',
                'first_name' => 'Laura',
                'last_name' => 'Sánchez',
                'tax_id' => '001-0045678-9',
                'email' => 'laura.sanchez@email.com',
                'phone' => '809-555-8901',
                'mobile' => '829-555-8901',
                'address' => 'Calle Padre Billini #234',
                'city' => 'Santo Domingo',
                'state' => 'Distrito Nacional',
                'postal_code' => '10108',
                'notes' => 'Profesora universitaria',
                'status' => true,
                'payment_terms' => 0,
                'credit_limit' => 0,
                'created_by' => $admin?->id,
            ],
            [
                'customer_code' => 'CLI-2025-0009',
                'customer_type' => 'company',
                'company_name' => 'Importadora de Equipos SAS',
                'first_name' => 'Miguel',
                'last_name' => 'Torres',
                'tax_id' => '130-56789-0',
                'email' => 'compras@importadoraequipos.com',
                'phone' => '809-555-9012',
                'mobile' => '829-555-9012',
                'address' => 'Av. Independencia #1234',
                'city' => 'Santo Domingo',
                'state' => 'Distrito Nacional',
                'postal_code' => '10109',
                'website' => 'https://www.importadoraequipos.com',
                'notes' => 'Cliente mayorista',
                'status' => true,
                'payment_terms' => 90,
                'credit_limit' => 500000,
                'created_by' => $admin?->id,
            ],
            [
                'customer_code' => 'CLI-2025-0010',
                'customer_type' => 'individual',
                'first_name' => 'Sofía',
                'last_name' => 'Vargas',
                'tax_id' => '001-0056789-0',
                'email' => 'sofia.vargas@email.com',
                'phone' => '809-555-0123',
                'mobile' => '829-555-0123',
                'address' => 'Calle Duarte #567',
                'city' => 'Santiago',
                'state' => 'Santiago',
                'postal_code' => '51000',
                'notes' => 'Cliente de Santiago - envíos especiales',
                'status' => true,
                'payment_terms' => 0,
                'credit_limit' => 0,
                'created_by' => $admin?->id,
            ],
        ];

        foreach ($customers as $customer) {
            Customer::create($customer);
        }

        $this->command->info('✅ Clientes creados exitosamente.');
    }
}

