# Database Configuration for Laravel Cloud
# This file defines the database configuration for Laravel Cloud deployment

database:
  type: "pgsql"
  host: "ep-crimson-bird-a46hyy47.aws-us-east-1.pg.laravel.cloud"
  port: "5432"
  database: "main"
  username: "laravel"
  password: "npg_DWalwCmzK7t5"
  
  # Laravel Cloud specific settings
  laravel_cloud:
    auto_migrate: true
    auto_seed: true
    backup_enabled: true
    
  # Connection settings
  connection:
    charset: "utf8mb4"
    collation: "utf8mb4_unicode_ci"
    strict: true
    engine: "InnoDB"
    
  # Migration settings
  migrations:
    table: "migrations"
    batch: 1
    
  # Seeder settings
  seeders:
    enabled: true
    force: true
