apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-cloud-config
  namespace: default
data:
  web_server: "apache"
  document_root: "public"
  php_version: "8.2"
  mod_rewrite: "true"
  allow_htaccess: "true"
  directory_index: "index.php index.html"
  error_pages_404: "/index.php"
  error_pages_403: "/index.php"
  error_pages_500: "/index.php"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: heroku/php:8.2-apache
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_KEY
          value: "base64:PfJiwGJ8YDmxKK8nE1H9JKTvOBJ0tkdwk3C027quLQw="
        - name: APP_DEBUG
          value: "false"
        - name: APP_URL
          value: "https://ticomsys-modernizado-main-oawkq1.laravel.cloud"
        - name: DB_CONNECTION
          value: "pgsql"
        - name: DB_HOST
          value: "ep-crimson-bird-a46hyy47.aws-us-east-1.pg.laravel.cloud"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "main"
        - name: DB_USERNAME
          value: "laravel"
        - name: DB_PASSWORD
          value: "npg_DWalwCmzK7t5"
        volumeMounts:
        - name: app-volume
          mountPath: /var/www/html
      volumes:
      - name: app-volume
        hostPath:
          path: /var/www/html
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
