services:
  - type: web
    name: ticomsys-moder-1
    env: php
    runtime: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-interaction
      php artisan key:generate --force
      mkdir -p storage/framework/{sessions,views,cache}
      mkdir -p storage/logs
      mkdir -p bootstrap/cache
      chmod -R 775 storage bootstrap/cache
      php artisan migrate --force
      php artisan db:seed --force
      cd frontend && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://ticomsys-moder-1.onrender.com
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ticomsys-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ticomsys-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: ticomsys-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ticomsys-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ticomsys-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_HTTP_ONLY
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      - key: FORCE_HTTPS
        value: true

databases:
  - name: ticomsys-db
    databaseName: ticomsys
    user: ticomsys_user
